nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Length', 'X-Total-Count']
        max_age: 3600
        allow_credentials: true
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
            max_age: 3600
            allow_credentials: true